//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeterReadings.Api.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MeterReadingCsvParserTestsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeterReadingCsvParserTestsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeterReadings.Api.Tests.MeterReadingCsvParserTestsResources", typeof(MeterReadingCsvParserTestsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId,MeterReadingDateTime,MeterReadValue,
        ///1,25/12/2020 12:34,2,
        ///2,26/12/2020 12:34,123,
        ///3,25/12/2020 12:34,432,.
        /// </summary>
        internal static string ParseMany_AllValid_ReturnsContracts {
            get {
                return ResourceManager.GetString("ParseMany_AllValid_ReturnsContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId,MeterReadingDateTime,MeterReadValue,
        ///sds,25/12/2020 12:34,2,
        ///2,26/12/2020 12:34,123,
        ///3,25/12/2020 12:34,432,.
        /// </summary>
        internal static string ParseMany_SingleInvalidAccount_ReturnsContracts {
            get {
                return ResourceManager.GetString("ParseMany_SingleInvalidAccount_ReturnsContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId,MeterReadingDateTime,MeterReadValue,
        ///1,25/12/2020 12:34,2,
        ///2,sdfsdfsd,123,
        ///3,25/12/2020 12:34,432,.
        /// </summary>
        internal static string ParseMany_SingleInvalidDate_ReturnsContracts {
            get {
                return ResourceManager.GetString("ParseMany_SingleInvalidDate_ReturnsContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId,MeterReadingDateTime,MeterReadValue,
        ///1,25/12/2020 12:34,2,
        ///2,26/12/2020 12:34,sfsdfd,
        ///3,25/12/2020 12:34,432,.
        /// </summary>
        internal static string ParseMany_SingleInvalidValue_ReturnsContracts {
            get {
                return ResourceManager.GetString("ParseMany_SingleInvalidValue_ReturnsContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId,MeterReadingDateTime,MeterReadValue,
        ///,25/12/2020 12:34,2,
        ///2,26/12/2020 12:34,123,
        ///3,25/12/2020 12:34,432,.
        /// </summary>
        internal static string ParseMany_SingleMissingAccount_ReturnsContracts {
            get {
                return ResourceManager.GetString("ParseMany_SingleMissingAccount_ReturnsContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId,MeterReadingDateTime,MeterReadValue,
        ///1,25/12/2020 12:34,2,
        ///2,,123,
        ///3,25/12/2020 12:34,432,.
        /// </summary>
        internal static string ParseMany_SingleMissingDate_ReturnsContracts {
            get {
                return ResourceManager.GetString("ParseMany_SingleMissingDate_ReturnsContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId,MeterReadingDateTime,MeterReadValue,
        ///1,25/12/2020 12:34,2,
        ///2,26/12/2020 12:34,,
        ///3,25/12/2020 12:34,432,.
        /// </summary>
        internal static string ParseMany_SingleMissingValue_ReturnsContracts {
            get {
                return ResourceManager.GetString("ParseMany_SingleMissingValue_ReturnsContracts", resourceCulture);
            }
        }
    }
}
